// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title ILiquidityProofVerifier
 * @notice Minimal verifier interface for the Noir `liquidity_proof` circuit.
 * @dev The concrete verifier is generated by `bb write_solidity_verifier` against
 *      `noir/liquidity_proof/`. Until the generated contract is placed at
 *      `contracts/verifiers/generated/LiquidityProofVerifier.sol`, consumers
 *      (e.g. {CrossChainLiquidityVault.releaseLiquidityWithProof}) MUST leave
 *      the verifier unset — attempts to use the ZK path will revert.
 *
 *      Public input layout (must match `noir/liquidity_proof/src/main.nr::main`):
 *        [0] lock_commitment        — Poseidon hash of the source-chain lock
 *        [1] pool_commitment        — Poseidon hash of destination pool state
 *        [2] nullifier              — release nullifier (replay prevention)
 *        [3] transfer_amount_hash   — Poseidon hash of the public transfer amount
 *        [4] current_timestamp      — destination-chain timestamp bound
 */
interface ILiquidityProofVerifier {
    /// @notice Verify an UltraHonk proof for the liquidity circuit.
    /// @param proof Serialized UltraHonk proof bytes.
    /// @param publicInputs Ordered public inputs (see interface docs).
    /// @return ok True if the proof is valid.
    /// @dev The generated Aztec `HonkVerifier.verify` is non-view because it
    ///      performs expensive precompile calls that solc cannot prove are
    ///      state-free; callers should treat the call as side-effect-free.
    function verify(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external returns (bool ok);
}
