// Contract ABIs for PIL v2
// These are simplified ABIs for the frontend - full ABIs are generated by Hardhat

export const PC3_ABI = [
  {
    inputs: [
      { name: 'encryptedPayload', type: 'bytes' },
      { name: 'stateCommitment', type: 'bytes32' },
      { name: 'nullifier', type: 'bytes32' },
      {
        name: 'proofs',
        type: 'tuple',
        components: [
          { name: 'validityProof', type: 'bytes' },
          { name: 'policyProof', type: 'bytes' },
          { name: 'nullifierProof', type: 'bytes' },
          { name: 'proofHash', type: 'bytes32' },
          { name: 'proofTimestamp', type: 'uint256' },
          { name: 'proofExpiry', type: 'uint256' },
        ],
      },
      { name: 'policyHash', type: 'bytes32' },
    ],
    name: 'createContainer',
    outputs: [{ name: 'containerId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'containerId', type: 'bytes32' }],
    name: 'verifyContainer',
    outputs: [
      {
        name: 'result',
        type: 'tuple',
        components: [
          { name: 'validityValid', type: 'bool' },
          { name: 'policyValid', type: 'bool' },
          { name: 'nullifierValid', type: 'bool' },
          { name: 'notExpired', type: 'bool' },
          { name: 'notConsumed', type: 'bool' },
          { name: 'failureReason', type: 'string' },
        ],
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'containerId', type: 'bytes32' }],
    name: 'consumeContainer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'containerId', type: 'bytes32' }],
    name: 'getContainer',
    outputs: [
      {
        name: 'container',
        type: 'tuple',
        components: [
          { name: 'encryptedPayload', type: 'bytes' },
          { name: 'stateCommitment', type: 'bytes32' },
          { name: 'nullifier', type: 'bytes32' },
          { name: 'policyHash', type: 'bytes32' },
          { name: 'chainId', type: 'uint64' },
          { name: 'createdAt', type: 'uint64' },
          { name: 'version', type: 'uint32' },
          { name: 'isVerified', type: 'bool' },
          { name: 'isConsumed', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalContainers',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalVerified',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export const PBP_ABI = [
  {
    inputs: [
      { name: 'policyType', type: 'bytes32' },
      { name: 'threshold', type: 'uint256' },
      { name: 'active', type: 'bool' },
      { name: 'expiry', type: 'uint256' },
    ],
    name: 'createPolicy',
    outputs: [{ name: 'policyId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'policyId', type: 'bytes32' },
      { name: 'proof', type: 'bytes' },
      { name: 'subject', type: 'address' },
    ],
    name: 'verifyCompliance',
    outputs: [{ name: 'compliant', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'policyId', type: 'bytes32' }],
    name: 'getPolicy',
    outputs: [
      {
        name: 'policy',
        type: 'tuple',
        components: [
          { name: 'policyType', type: 'bytes32' },
          { name: 'threshold', type: 'uint256' },
          { name: 'active', type: 'bool' },
          { name: 'expiry', type: 'uint256' },
          { name: 'creator', type: 'address' },
        ],
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalPolicies',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export const EASC_ABI = [
  {
    inputs: [
      { name: 'stateRoot', type: 'bytes32' },
      { name: 'executionEnvHash', type: 'bytes32' },
      { name: 'metadata', type: 'bytes' },
    ],
    name: 'createCommitment',
    outputs: [{ name: 'commitmentId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'commitmentId', type: 'bytes32' },
      { name: 'newStateRoot', type: 'bytes32' },
      { name: 'transitionProof', type: 'bytes' },
    ],
    name: 'recordTransition',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'commitmentId', type: 'bytes32' }],
    name: 'getCommitment',
    outputs: [
      {
        name: 'commitment',
        type: 'tuple',
        components: [
          { name: 'stateRoot', type: 'bytes32' },
          { name: 'executionEnvHash', type: 'bytes32' },
          { name: 'transitionCount', type: 'uint256' },
          { name: 'lastUpdated', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export const CDNA_ABI = [
  {
    inputs: [{ name: 'nullifier', type: 'bytes32' }],
    name: 'isNullifierConsumed',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'nullifier', type: 'bytes32' },
      { name: 'domainId', type: 'uint256' },
    ],
    name: 'consumeNullifier',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'nullifier', type: 'bytes32' }],
    name: 'getNullifierInfo',
    outputs: [
      {
        name: 'info',
        type: 'tuple',
        components: [
          { name: 'consumed', type: 'bool' },
          { name: 'domainId', type: 'uint256' },
          { name: 'consumedAt', type: 'uint256' },
          { name: 'consumer', type: 'address' },
        ],
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export const ORCHESTRATOR_ABI = [
  {
    inputs: [
      { name: 'stateCommitment', type: 'bytes32' },
      { name: 'nullifier', type: 'bytes32' },
      { name: 'validityProof', type: 'bytes' },
      { name: 'policyProof', type: 'bytes' },
      { name: 'nullifierProof', type: 'bytes' },
      { name: 'proofHash', type: 'bytes32' },
      { name: 'recipient', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'executePrivateTransfer',
    outputs: [{ name: 'transferId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSystemStatus',
    outputs: [
      {
        name: 'status',
        type: 'tuple',
        components: [
          { name: 'pc3Active', type: 'bool' },
          { name: 'pbpActive', type: 'bool' },
          { name: 'eascActive', type: 'bool' },
          { name: 'cdnaActive', type: 'bool' },
          { name: 'totalOperations', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
